spring:
  banner:
    location: banner.txt
  application:
    name: admin-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
server:
  port: 9090