spring:
  banner:
    location: banner.txt
  application:
    name: admin-server
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka
    fetch-registry: true
server:
  port: ${ADMIN_SERVER_PORT:9090}
