services:
  config-server:
    image: fortuneiyke/ecommerce-config-server:latest
    ports:
      - ${CONFIG_SERVER_PORT:-8888}:8888
    networks:
      - ecommerce-network
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=${CONFIG_GIT_URI}
      - SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL=main

  service-discovery:
    image: fortuneiyke/ecommerce-service-discovery:latest
    ports:
      - ${EUREKA_PORT:-8761}:8761
    networks:
      - ecommerce-network
    environment:
      - EUREKA_INSTANCE_HOSTNAME=service-discovery

  auth-service:
    image: fortuneiyke/ecommerce-auth-service:latest
    ports:
      - ${AUTH_SERVICE_PORT:-8081}:8081
    networks:
      - ecommerce-network
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}

  customer-service:
    image:  fortuneiyke/ecommerce-customer-service:latest
    ports:
      - ${CUSTOMER_SERVICE_PORT:-8080}:8080
    networks:
      - ecommerce-network
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}

  product-service:
    image:  fortuneiyke/ecommerce-product-service:latest
    ports:
      - ${PRODUCT_SERVICE_PORT:-8082}:8082
    networks:
      - ecommerce-network
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}

  inventory-service:
    image:  fortuneiyke/ecommerce-inventory-service:latest
    ports:
      - ${INVENTORY_SERVICE_PORT:-8083}:8083
    networks:
      - ecommerce-network
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}

  order-service:
    image: fortuneiyke/ecommerce-order-service:latest
    ports:
      - ${ORDER_SERVICE_PORT:-8084}:8084
    networks:
      - ecommerce-network
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}

  payment-service:
    image:  fortuneiyke/ecommerce-payment-service:latest
    ports:
      - ${PAYMENT_SERVICE_PORT:-8085}:8085
    networks:
      - ecommerce-network
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - INTERSWITCH_MERCHANT_CODE=${INTERSWITCH_MERCHANT_CODE}
      - INTERSWITCH_CURRENCY=${INTERSWITCH_CURRENCY}
      - INTERSWITCH_CLIENT_ID=${INTERSWITCH_CLIENT_ID}
      - INTERSWITCH_SECRET_KEY=${INTERSWITCH_SECRET_KEY}

  notification-service:
    image:  fortuneiyke/ecommerce-notification-service:latest
    ports:
      - ${NOTIFICATION_SERVICE_PORT:-8086}:8086
    networks:
      - ecommerce-network
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}

  cart-service:
    image:  fortuneiyke/ecommerce-cart-service:latest
    ports:
      - ${CART_SERVICE_PORT:-8087}:8087
    networks:
      - ecommerce-network
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}

  api-gateway:
    image:  fortuneiyke/ecommerce-api-gateway:latest
    ports:
      - ${API_GATEWAY_PORT:-8000}:8000
    networks:
      - ecommerce-network
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888

  admin-server:
    image:  fortuneiyke/ecommerce-admin-server:latest
    ports:
      - ${ADMIN_SERVER_PORT:-9090}:9090
    networks:
      - ecommerce-network
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888

  api-docs:
    image:  fortuneiyke/ecommerce-api-docs:latest
    ports:
      - ${API_DOCS_PORT:-9091}:9091
    networks:
      - ecommerce-network
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - ${RABBITMQ_PORT:-5672}:5672
      - 15672:15672
    networks:
      - ecommerce-network
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}

  postgres:
    image: postgres:16
    ports:
      - ${DB_PORT:-5432}:5432
    networks:
      - ecommerce-network
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  zipkin:
    image: openzipkin/zipkin
    ports:
      - ${ZIPKIN_PORT:-9411}:9411
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
