
spring:
  application:
    name: api-gateway-service
  banner:
    location: banner.txt
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: customer-service
              uri: lb://CUSTOMER-SERVICE
              predicates:
                - Path=/users/**
              filters:
                - RewritePath=/users/(?<segment>.*), /api/v1/customer/${segment}
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**
              filters:
                - RewritePath=/auth/(?<segment>.*), /api/v1/auth/${segment}
            - id: cart-service
              uri: lb://CART-SERVICE
              predicates:
                - Path=/cart/**
              filters:
                - RewritePath=/cart/(?<segment>.*), /api/v1/cart/${segment}
            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/product/**
              filters:
                - RewritePath=/product/(?<segment>.*), /api/v1/product/${segment}
  main:
    web-application-type: reactive
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    org.springframework.security: trace