services:
  auth-service:
    image: fortuneiyke/ecommerce-auth-service:latest
    ports:
      - ${AUTH_SERVICE_PORT:-8081}:8081
    networks:
      - auth-network
#    depends_on:
#      - auth-postgres
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=${DATABASE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://${EUREKA_HOST}:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}

#  auth-postgres:
#    image: postgres:16
#    ports:
#      - ${AUTH_DB_PORT:-5433}:5432
#    networks:
#      - auth-network
#    environment:
#      - POSTGRES_DB=auth_db
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=password

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - ${RABBITMQ_PORT:-5672}:5672
      - 15672:15672
    networks:
      - auth-network
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}

networks:
  auth-network:
    driver: bridge
