api-gateway-url: http://${API_GATEWAY_HOST:localhost}:${API_GATEWAY_PORT:8081}
app:
  title: "INVENTORY-SERVICE"
  version: "1.0.0"
  description: "API documentation for My Inventory Service Microservice"
  url: ${api-gateway-url}
spring:
  banner:
    location: banner.txt
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ecommercems}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: inventory-service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
api:
  url: '/api/v1/inventory'
rsa:
  public-key: classpath:certs/public.pem
server:
  port: ${INVENTORY_SERVICE_PORT:0}
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
