spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fortune/ecommerce-config.git
          default-label: main
server:
  port: 8888
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka