services:
  customer-service:
    image: fortuneiyke/ecommerce-customer-service:latest
    ports:
      - ${CUSTOMER_SERVICE_PORT:-8080}:8080
    networks:
      - customer-network
    depends_on:
      - customer-postgres
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=jdbc:postgresql://customer-postgres:5432/customer_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}

  customer-postgres:
    image: postgres:16
    ports:
      - ${CUSTOMER_DB_PORT:-5434}:5432
    networks:
      - customer-network
    environment:
      - POSTGRES_DB=customer_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - ${RABBITMQ_PORT:-5672}:5672
      - 15672:15672
    networks:
      - customer-network
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}

networks:
  customer-network:
    driver: bridge
